spring.application.name=cv-generator
server.port=${SERVER_PORT:8090}
spring.mvc.problemdetails.enabled=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
